#devopsdemo - pipeline

name: $(date:yyyyMMdd)$(rev:.rr) #20190910.00

stages: 
  - stage:  'build'
    condition: succeeded()
    displayName: 'build-mvc'
    jobs:
      - job:
        condition: succeeded()
        displayName: 'build-process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: UseDotNet@2
            displayName: 'dotnet installer'
            input:
              version: '2.2.401'
          - script: |
              dotnet build

  - stage:  'test'
    condition: succeeded()
    displayName: 'test-mvc'
    jobs:
      - job:
        condition: succeeded()
        displayName: 'test-process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              dotnet test

  - stage:  'pack'
    condition: succeeded()
    displayName: 'pack-mvc'
    dependsOn:
      - test
    jobs:
      - job:
        condition: succeeded()
        displayName: 'pack-process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              dotnet publish

  - stage:  'deploy'
    condition: succeeded()
    displayName: 'deploy-mvc'
    dependsOn:
      - test
    jobs:
      - job:
        condition: succeeded()
        displayName: 'deploy-process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              echo 'deploy passed ...'

trigger:
  branches:
    include:
      - master

variables:
  testVar: 'tuesday'